In [1]:
import keras
import tensorflow as tf
print(keras.__version__)
print(tf.__version__)

2.6.0
2.6.1


In [2]:
import numpy as np

# 하나의 원소가 샘플. 하나의 문장.
samples = ['The cat sat on the mat.', 'The dog ate my homework.']

In [3]:
# 단어:인덱스
token_index = {}

for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1
            
max_length = 10
token_index

{'The': 1,
 'cat': 2,
 'sat': 3,
 'on': 4,
 'the': 5,
 'mat.': 6,
 'dog': 7,
 'ate': 8,
 'my': 9,
 'homework.': 10}

In [4]:
# 결과를 저장할 배열(0으로 이루어진 벡터)
# max_length는 사용할 단어수
results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
print(results.shape, results, sep='\n')

(2, 10, 11)
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [5]:
token_index.get(word)

10

In [6]:
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.  # 행, 열, 인덱스를 1로 치환 

In [7]:
results

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

### 케라스를 활용 원핫 인코딩

In [8]:
from keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat.', 'The dog ate my homework.']

In [9]:
# 가장 빈도가 높은 1,000개의 단어만 선택하도록 Tokenizer 객체를 만듭니다.
tokenizer = Tokenizer(num_words=1000)

# 단어 인덱스를 구축합니다.
tokenizer.fit_on_texts(samples)

# 문자열을 정수 인덱스의 리스트로 변환합니다.
sequences = tokenizer.texts_to_sequences(samples)
sequences

[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]

In [41]:
np.array(sequences).shape

<ipython-input-41-bcb3eb62cab1>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array(sequences).shape


(2,)

In [10]:
one_hot = tokenizer.texts_to_matrix(samples, mode='binary')
one_hot.shape, one_hot

((2, 1000),
 array([[0., 1., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]]))

In [11]:
tokenizer.word_index

{'the': 1,
 'cat': 2,
 'sat': 3,
 'on': 4,
 'mat': 5,
 'dog': 6,
 'ate': 7,
 'my': 8,
 'homework': 9}

In [12]:
# 계산된 단어 인덱스를 구합니다.
word_index = tokenizer.word_index
print(word_index)
print('Found %s unique tokens.' % len(word_index))

{'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}
Found 9 unique tokens.


### 원핫 해싱
* 원핫 인코딩의 변종중의 하나는 원-핫 해싱(one-hot hashing)기법입니다.
* 고유한 토큰의 수가 너무 커서 다루기 어려울 때 사용.
    * 각 단어에 명시적으로 인덱스를 할당하고 이 인덱스를 딕셔너리에 저장하지 않고, 단어를 해싱한다.

In [13]:
samples = ['The cat sat on the mat.', 'The dog ate my homework.']

# 단어를 크기가 1,000인 벡터로 저장합니다.
# 1,000개(또는 그이상)의 단어가 있다면 해싱 충돌이 늘어나고 인코딩의 정확도가 감소될 것입니다
dimensionality = 1000
max_length = 10

In [14]:
results = np.zeros((len(samples), max_length, dimensionality))
print(results.shape)

for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        # 단어를 해싱하여 0과 1,000 사이의 랜덤한 정수 인덱스로 변환합니다.
        index = abs(hash(word)) % dimensionality
        results[i, j, index] = 1.

(2, 10, 1000)


### 임베딩 실습

In [15]:
from keras.layers import Embedding

In [16]:
embedding_layer = Embedding(1000, 64) # Embedding(개수, 차원수)

print( type(embedding_layer), embedding_layer)

<class 'keras.layers.embeddings.Embedding'> <keras.layers.embeddings.Embedding object at 0x00000271F9C1EEE0>


In [17]:
from keras.datasets import imdb
from keras import preprocessing

In [18]:
# 특성으로 사용할 단어의 수
max_features = 10000

# 정수 리스트로 데이터를 로드합니다.
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

In [19]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [20]:
print(len(X_train[0]), X_train[0], sep='\n')
print()
print(y_train[0])

218
[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]

1


In [21]:
# 리스트를 (samples, maxlen) 크기의 2D 정수 텐서로 변환합니다.
maxlen = 50

X_train_n = preprocessing.sequence.pad_sequences(X_train, maxlen=maxlen)
X_test_n = preprocessing.sequence.pad_sequences(X_test, maxlen=maxlen)

In [22]:
print("변경 전 : " , X_train.shape, X_test.shape)
print("변경 후 : ", X_train_n.shape, X_test_n.shape)

변경 전 :  (25000,) (25000,)
변경 후 :  (25000, 50) (25000, 50)


In [23]:
X_train_n[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32])

In [24]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding

In [25]:
model = Sequential()
# Embedding(개수, 차원수)
model.add(Embedding(10000,8, input_length=maxlen)) # None, 50, 8
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 50, 8)             80000     
_________________________________________________________________
flatten (Flatten)            (None, 400)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 401       
Total params: 80,401
Trainable params: 80,401
Non-trainable params: 0
_________________________________________________________________


In [26]:
%%time 

# 분류기를 추가합니다.
model.compile(optimizer='rmsprop', 
              loss='binary_crossentropy', 
              metrics=['acc'])

history = model.fit(X_train_n, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.2)

Epoch 1/10
625/625 [==============================] - 2s 2ms/step - loss: 0.6451 - acc: 0.6565 - val_loss: 0.5456 - val_acc: 0.7590
Epoch 2/10
625/625 [==============================] - 1s 1ms/step - loss: 0.4522 - acc: 0.8056 - val_loss: 0.4328 - val_acc: 0.7982
Epoch 3/10
625/625 [==============================] - 1s 1ms/step - loss: 0.3654 - acc: 0.8412 - val_loss: 0.4070 - val_acc: 0.8092
Epoch 4/10
625/625 [==============================] - 1s 1ms/step - loss: 0.3241 - acc: 0.8622 - val_loss: 0.3993 - val_acc: 0.8142
Epoch 5/10
625/625 [==============================] - 1s 1ms/step - loss: 0.2958 - acc: 0.8756 - val_loss: 0.4001 - val_acc: 0.8172
Epoch 6/10
625/625 [==============================] - 1s 1ms/step - loss: 0.2729 - acc: 0.8865 - val_loss: 0.4054 - val_acc: 0.8174
Epoch 7/10
625/625 [==============================] - 1s 1ms/step - loss: 0.2524 - acc: 0.8974 - val_loss: 0.4108 - val_acc: 0.8140
Epoch 8/10
625/625 [==============================] - 1s 1ms/step - loss: 0.

### 간단한 RNN 신경망 구현해보기

In [27]:
import tensorflow as tf
import keras

In [28]:
import numpy as np

In [29]:
for i in range(10):
    lst = list(range(i, i+5))
    print(lst)

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9, 10]
[7, 8, 9, 10, 11]
[8, 9, 10, 11, 12]
[9, 10, 11, 12, 13]


In [30]:
X = []
Y = []
for i in range(10):
    lst = list(range(i, i+5))
    X.append( [ [c/10] for c in lst]  )  # 문제
    Y.append( (i+5)/10  )  #
    
X = np.array(X)
Y = np.array(Y)

print( X.shape, Y.shape ) # 10개의 샘플 (5,1), 다음 0.5
print( X[0], Y[0])
print( X[1], Y[1])

(10, 5, 1) (10,)
[[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6


In [31]:
for i in range(len(X)):
    print(X[i], Y[i])
print(X.shape, Y.shape)

[[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9
[[0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]] 1.0
[[0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]] 1.1
[[0.7]
 [0.8]
 [0.9]
 [1. ]
 [1.1]] 1.2
[[0.8]
 [0.9]
 [1. ]
 [1.1]
 [1.2]] 1.3
[[0.9]
 [1. ]
 [1.1]
 [1.2]
 [1.3]] 1.4
(10, 5, 1) (10,)


In [39]:
print(X.shape, X, sep='\n')

(10, 5, 1)
[[[0. ]
  [0.1]
  [0.2]
  [0.3]
  [0.4]]

 [[0.1]
  [0.2]
  [0.3]
  [0.4]
  [0.5]]

 [[0.2]
  [0.3]
  [0.4]
  [0.5]
  [0.6]]

 [[0.3]
  [0.4]
  [0.5]
  [0.6]
  [0.7]]

 [[0.4]
  [0.5]
  [0.6]
  [0.7]
  [0.8]]

 [[0.5]
  [0.6]
  [0.7]
  [0.8]
  [0.9]]

 [[0.6]
  [0.7]
  [0.8]
  [0.9]
  [1. ]]

 [[0.7]
  [0.8]
  [0.9]
  [1. ]
  [1.1]]

 [[0.8]
  [0.9]
  [1. ]
  [1.1]
  [1.2]]

 [[0.9]
  [1. ]
  [1.1]
  [1.2]
  [1.3]]]


In [32]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10,
                              return_sequences=False, # False : many to one, True : many to many 같이 숨겨진 결과도 보여준다.
                              input_shape=[5,1]),
    tf.keras.layers.Dense(1)
])

In [33]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(X, Y, epochs=50, verbose=1)

Epoch 1/50
1/1 [==============================] - 1s 622ms/step - loss: 2.5518
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 2.4588
Epoch 3/50
1/1 [==============================] - 0s 4ms/step - loss: 2.3674
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 2.2777
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 2.1898
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 2.1037
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 2.0195
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 1.9372
Epoch 9/50
1/1 [==============================] - 0s 4ms/step - loss: 1.8567
Epoch 10/50
1/1 [==============================] - 0s 7ms/step - loss: 1.7780
Epoch 11/50
1/1 [==============================] - 0s 4ms/step - loss: 1.7012
Epoch 12/50
1/1 [==============================] - 0s 4ms/step - loss: 1.6264
Epoch 13/50
1/1 [==============================] - 0s 4ms/step - loss: 

In [36]:
pred = model.predict(X)
pred

array([[0.4688046 ],
       [0.52546537],
       [0.5722122 ],
       [0.6084702 ],
       [0.6346126 ],
       [0.6516434 ],
       [0.6608853 ],
       [0.66374207],
       [0.66154885],
       [0.65548444]], dtype=float32)