# CNN 알고리즘

* 입력 : 이미지 데이터
* CNN
  * Convolution 계층
  * Pooling 계층
  * FCL보다 성능 우수

In [ ]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras import layers

In [ ]:
model = models.Sequential()
model.add( layers.Conv2D( 32, (3,3), activation='relu', input_shape=(28,28,1) ) )
model.add( layers.MaxPooling2D( (2,2) ) )
model.add( layers.Flatten()) # 1차원으로 펼쳐준다
model.add( layers.Dense(64, activation='relu'))
model.add( layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                346176    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                650       
Total params: 347,146
Trainable params: 347,146
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#from keras.datasets import mnist
#from keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [ ]:
train_images.shape, train_labels.shape

((60000, 28, 28), (60000,))

In [ ]:
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

print(train_labels[0:10])
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
print(train_labels[0:10])

[5 0 4 1 9 2 1 3 1 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
%%time

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=20, batch_size=64)

Epoch 1/20
938/938 [==============================] - 6s 6ms/step - loss: 0.6739 - accuracy: 0.8190
Epoch 2/20
938/938 [==============================] - 5s 6ms/step - loss: 0.2977 - accuracy: 0.9135
Epoch 3/20
938/938 [==============================] - 5s 6ms/step - loss: 0.2495 - accuracy: 0.9271
Epoch 4/20
938/938 [==============================] - 5s 6ms/step - loss: 0.2156 - accuracy: 0.9366
Epoch 5/20
938/938 [==============================] - 5s 6ms/step - loss: 0.1903 - accuracy: 0.9432
Epoch 6/20
938/938 [==============================] - 5s 6ms/step - loss: 0.1705 - accuracy: 0.9498
Epoch 7/20
938/938 [==============================] - 5s 5ms/step - loss: 0.1550 - accuracy: 0.9543
Epoch 8/20
938/938 [==============================] - 5s 5ms/step - loss: 0.1416 - accuracy: 0.9584
Epoch 9/20
938/938 [==============================] - 5s 5ms/step - loss: 0.1311 - accuracy: 0.9616
Epoch 10/20
938/938 [==============================] - 5s 6ms/step - loss: 0.1215 - accuracy: 0.9639

In [ ]:
# 2min 22s
# loss: 0.0690 - accuracy: 0.9793

In [ ]:
%%time

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=5, batch_size=64, validation_data=(test_images, test_labels))

Epoch 1/5
938/938 [==============================] - 6s 6ms/step - loss: 0.0659 - accuracy: 0.9804 - val_loss: 0.0806 - val_accuracy: 0.9738
Epoch 2/5
938/938 [==============================] - 6s 6ms/step - loss: 0.0632 - accuracy: 0.9814 - val_loss: 0.0782 - val_accuracy: 0.9746
Epoch 3/5
938/938 [==============================] - 6s 6ms/step - loss: 0.0608 - accuracy: 0.9817 - val_loss: 0.0699 - val_accuracy: 0.9782
Epoch 4/5
938/938 [==============================] - 6s 6ms/step - loss: 0.0584 - accuracy: 0.9825 - val_loss: 0.0692 - val_accuracy: 0.9763
Epoch 5/5
938/938 [==============================] - 6s 6ms/step - loss: 0.0564 - accuracy: 0.9832 - val_loss: 0.0692 - val_accuracy: 0.9765
CPU times: user 27 s, sys: 4.09 s, total: 31.1 s
Wall time: 29.4 s


In [ ]:
# 29.4 s
# loss: 0.0564 - accuracy: 0.9832 - val_loss: 0.0692 - val_accuracy: 0.9765

In [ ]:
model = models.Sequential()
model.add( layers.Conv2D( 32, (3,3), activation='relu', input_shape=(28,28,1) ) )
model.add( layers.Conv2D( 32, (3,3), activation='relu', input_shape=(28,28,1) ) )
model.add( layers.MaxPooling2D( (2,2) ) )
model.add( layers.Flatten()) # 1차원으로 펼쳐준다
model.add( layers.Dense(64, activation='relu'))
model.add( layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 24, 24, 32)        9248      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 4608)              0         
_________________________________________________________________
dense_6 (Dense)              (None, 64)                294976    
_________________________________________________________________
dense_7 (Dense)              (None, 10)                650       
Total params: 305,194
Trainable params: 305,194
Non-trainable params: 0
________________________________________________

In [ ]:
%%time

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=25, batch_size=64, validation_data=(test_images, test_labels))

Epoch 1/25
938/938 [==============================] - 9s 9ms/step - loss: 0.6001 - accuracy: 0.8256 - val_loss: 0.4470 - val_accuracy: 0.8615
Epoch 2/25
938/938 [==============================] - 8s 8ms/step - loss: 0.2303 - accuracy: 0.9312 - val_loss: 0.1970 - val_accuracy: 0.9426
Epoch 3/25
938/938 [==============================] - 8s 8ms/step - loss: 0.1763 - accuracy: 0.9474 - val_loss: 0.1509 - val_accuracy: 0.9551
Epoch 4/25
938/938 [==============================] - 7s 8ms/step - loss: 0.1466 - accuracy: 0.9556 - val_loss: 0.1474 - val_accuracy: 0.9541
Epoch 5/25
938/938 [==============================] - 8s 8ms/step - loss: 0.1251 - accuracy: 0.9622 - val_loss: 0.1084 - val_accuracy: 0.9660
Epoch 6/25
938/938 [==============================] - 8s 8ms/step - loss: 0.1079 - accuracy: 0.9665 - val_loss: 0.1098 - val_accuracy: 0.9667
Epoch 7/25
938/938 [==============================] - 8s 8ms/step - loss: 0.0966 - accuracy: 0.9704 - val_loss: 0.0976 - val_accuracy: 0.9697
Epoch 

In [ ]:
# 3min 22s
# loss: 0.0251 - accuracy: 0.9923 - val_loss: 0.0435 - val_accuracy: 0.9869